### ISSUE TITLE
The test results of Farmland is far worse than your paper 

### ISSUE THREAD

**Issue by fangs99** [yizhilanmaodhh/change-detection-MSDC#3]
Many thanks your for works.  Becuase we don't have other SAR images tested in your paper, we test the "Farmland" SAR image after modifying the error in loading data, as the other issue pointed out. 

However, the results of ACC is far worse than your paper. The kappa value in tabale II in your paper is 90.64 when LR is set to be  0.01, however using the same LR=0.01, our results only reaches 0.691. And the OE at best is 3149. 

![Uploading plt_acc_loss.png…]()

We wonder what's wrong about the source code. Further, is your code in need of special training tricks which are not given out in your code or paper?

**Comment by yizhilanmaodhh** [comment]
Because our method is unsupervised, the detection results are heavily influenced by parameter initialization:
1.Is your&nbsp;Pytorch version=1.1.0?&nbsp;In our experiments, we also switched to the pytorch version and found that the detection results dropped significantly.
2.&nbsp;What is your epoch set to? The output of different epochs may vary.
3.&nbsp;Our results are selected&nbsp; by multiple runs.
Above for reference.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yizhilanmaodhh/change-detection-MSDC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月18日(星期六) 中午11:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yizhilanmaodhh/change-detection-MSDC] The test results of Farmland is far worse than your paper  (Issue #3)





 
Many thanks your for works.  Becuase we don't have other SAR images tested in your paper, we test the "Farmland" SAR image after modifying the error in loading data, as the other issue pointed out.
 
However, the results of ACC is far worse than your paper. The kappa value in tabale II in your paper is 90.64 when LR is set to be  0.01, however using the same LR=0.01, our results only reaches 0.691. And the OE at best is 3149.
 

 
We wonder what's wrong about the source code. Further, is your code in need of special training tricks which are not given out in your code or paper?

**Comment by fangs99** [comment]
Many thanks for your prompt reply.

About the first point , we unserstand. 
As to the epoch, we set it to be 50, and the training takes almost 8 hours using one NVIDIA 1080 GPU.  The best results occur in the 37th epoch.
About the third point, thanks for your frank reply. Because this is in unsupervised mode, we don't  consider this point.
